const enumLabelMap: Record<string, string> = {
  OWNER: "Dono",
  ADMIN: "Administrador",
  MANAGER: "Gerente",
  USER: "Usuário",
  VIEWER: "Visualizador",
  CLIENT: "Cliente",
  NEW: "Novo",
  QUALIFIED: "Qualificado",
  PROPOSAL: "Proposta",
  NEGOTIATION: "Negociação",
  WON: "Ganho",
  LOST: "Perdido",
  TASK: "Tarefa",
  CALL: "Ligação",
  MEETING: "Reunião",
  NOTE: "Anotação",
  OPEN: "Aberto",
  PENDING: "Pendente",
  RESOLVED: "Resolvido",
  CLOSED: "Fechado",
  LOW: "Baixa",
  MEDIUM: "Média",
  HIGH: "Alta",
  URGENT: "Urgente",
  PLANNED: "Planejada",
  ACTIVE: "Ativa",
  PAUSED: "Pausada",
  COMPLETED: "Concluída",
  ONBOARDING: "Implantação",
  AT_RISK: "Em risco",
  CHURNED: "Cancelado",
  DONE: "Concluído",
  BLOCKED: "Bloqueado",
  CANCELED: "Cancelado",
  EXPIRED: "Expirado",
  UPCOMING: "A vencer",
  IN_NEGOTIATION: "Em negociação",
  RENEWED: "Renovado",
  DRAFT: "Rascunho",
  SENT: "Enviado",
  ACCEPTED: "Aceito",
  REJECTED: "Rejeitado",
  APPROVED: "Aprovado",
  NONE: "Nenhum",
  PERCENT: "Percentual",
  FIXED: "Fixo",
  SUCCESS: "Sucesso",
  FAILED: "Falhou",
  SKIPPED: "Ignorado",
  ORG: "Organização",
  UNIT: "Unidade",
  TEAM: "Time",
  OWNED_ONLY: "Somente responsável",
  INVITED: "Convidado",
  DISABLED: "Desativado",
  USED: "Utilizado",
  LEAD_CREATED: "Potencial criado",
  DEAL_STAGE_CHANGED: "Etapa da oportunidade alterada",
  TICKET_CREATED: "Chamado criado",
  HEALTH_SCORE_DROPPED: "Pontuação de saúde caiu",
  RENEWAL_DUE_SOON: "Renovação próxima",
  CREATE_ACTIVITY: "Criar atividade",
  ASSIGN_OWNER: "Atribuir responsável",
  CREATE_TICKET: "Criar chamado",
  NOTIFY_IN_APP: "Notificar no app",
  UPDATE_DEAL_STAGE: "Atualizar etapa da oportunidade",
  LOGIN: "Entrar",
  LOGOUT: "Sair",
  CREATE: "Criação",
  UPDATE: "Atualização",
  DELETE: "Exclusão",
  form: "Formulário",
  web: "Web",
  manual: "Manual",
  import: "Importação",
  activity: "Atividade",
  ticket: "Chamado",
  "deal-change": "Mudança de oportunidade",
  renewal: "Renovação",
  "lead.created": "Potencial criado",
  "deal.updated": "Oportunidade atualizada",
  "ticket.created": "Chamado criado",
  "proposal.approved": "Proposta aprovada",
  "workflow.run": "Execução de fluxo",
  auth: "Autenticação",
  company: "Empresa",
  contact: "Contato",
  deal: "Oportunidade",
  "cs-profile": "Perfil de CS",
  "cs-health": "Saúde do cliente",
  contract: "Contrato",
  campaign: "Campanha",
  utm: "UTM",
  webhook: "Webhook",
  proposal: "Proposta",
  PROPOSAL: "Proposta",
  approval: "Aprovação",
  "approval-request": "Solicitação de aprovação",
  "catalog-item": "Item de catálogo",
  workflow: "Fluxo",
  "workflow-run": "Execução de fluxo",
  unit: "Unidade",
  team: "Time",
  membership: "Vínculo",
  territory: "Território",
  security: "Segurança",
  compliance: "Conformidade",
  user: "Usuário",
  notification: "Notificação",
  export: "Exportação",
};

export const formatEnumLabel = (value?: string | null) => {
  if (!value) return "-";
  return enumLabelMap[value] ?? value;
};
